#!/bin/bash
# AdminDetailsPage Quick Setup Script
# This script provides step-by-step instructions to set up the AdminDetailsPage feature
# Note: Some steps require manual action in Supabase dashboard

echo "========================================="
echo "AdminDetailsPage - Quick Setup Guide"
echo "========================================="
echo ""

# Step 1: Apply Database Migration
echo "Step 1: Applying Database Migration..."
echo "Command: supabase db push || supabase migration up"
echo ""
echo "⚠️  Manual Option:"
echo "   1. Go to Supabase Dashboard"
echo "   2. Select your project"
echo "   3. Go to SQL Editor"
echo "   4. Create a new query"
echo "   5. Copy contents of: supabase/migrations/20260403_admin_details.sql"
echo "   6. Run the query"
echo ""

# Step 2: Create Storage Bucket
echo "Step 2: Creating Storage Bucket..."
echo ""
echo "⚠️  Manual Steps in Supabase Dashboard:"
echo "   1. Go to Storage → Buckets"
echo "   2. Click 'Create a new bucket'"
echo "   3. Bucket name: admin-documents"
echo "   4. Make sure 'Public bucket' is TURNED OFF"
echo "   5. Click 'Create bucket'"
echo ""

# Step 3: Set Up Storage Policies
echo "Step 3: Setting Up Storage Policies..."
echo ""
echo "Option A - Via SQL (Recommended):"
echo "   1. Go to Supabase SQL Editor"
echo "   2. Create a new query"
echo "   3. Copy contents of: supabase/migrations/20260403_storage_policies.sql"
echo "   4. Run the query"
echo ""
echo "Option B - Via Dashboard (If SQL fails):"
echo "   1. Go to Storage → admin-documents bucket"
echo "   2. Click 'Policies' tab"
echo "   3. Click 'Create a new policy'"
echo "   4. Create 4 policies for: SELECT, INSERT, UPDATE, DELETE"
echo "   5. Use this condition for each:"
echo "      bucket_id = 'admin-documents' AND"
echo "      EXISTS ("
echo "        SELECT 1 FROM members"
echo "        WHERE members.auth_user_id = auth.uid()"
echo "        AND members.role = 'super_admin'"
echo "      )"
echo ""

# Step 4: Code is Ready
echo "Step 4: Code Setup (Already Done!)"
echo "   ✅ AdminDetailsPage component created"
echo "   ✅ Routes added to App.tsx"
echo "   ✅ Sidebar navigation updated"
echo "   ✅ All imports configured"
echo ""

# Step 5: Verify Installation
echo "Step 5: Verify Installation"
echo ""
echo "Check these files exist:"
echo "   ✓ src/pages/admin/AdminDetailsPage.tsx"
echo "   ✓ supabase/migrations/20260403_admin_details.sql"
echo "   ✓ supabase/migrations/20260403_storage_policies.sql"
echo ""

echo "Check these files were modified:"
echo "   ✓ src/components/admin/AdminSidebar.tsx"
echo "   ✓ src/App.tsx"
echo ""

# Step 6: Test
echo "Step 6: Test the Feature"
echo ""
echo "Access via:"
echo "   URL: http://localhost:5173/admin/details (or your dev server)"
echo "   Sidebar: Admin Details (only visible to super_admin)"
echo ""

echo "Test Actions:"
echo "   1. Upload a PDF/Word/Excel file"
echo "   2. Add a contact (Name, Batch, Phone)"
echo "   3. Download contact as file"
echo "   4. Edit contact"
echo "   5. Delete contact"
echo "   6. Add a patron (Name, Patron No)"
echo "   7. Download patron as file"
echo "   8. Edit patron"
echo "   9. Delete patron"
echo ""

echo "========================================="
echo "Setup Complete!"
echo "========================================="
echo ""
echo "Next Steps:"
echo "1. Copy the SQL commands and run in Supabase"
echo "2. Create the storage bucket manually"
echo "3. Set up the storage policies"
echo "4. Start your dev server: npm run dev"
echo "5. Login as super_admin to test"
echo ""
echo "For detailed info, see: ADMIN_DETAILS_SETUP.md"
echo ""
