-- Migration: create school_quiz_order table
-- Generated: 2026-02-28
-- Description: stores a per-school question order for each password-based quiz

create table if not exists public.school_quiz_order (
    id bigint generated by default as identity primary key,
    school_name text not null,
    quiz_password_id bigint not null references public.quiz_passwords(id) on delete cascade,
    order_ids text[] not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- ensure each school/quiz combination is unique
create unique index if not exists school_quiz_order_school_quiz_idx
    on public.school_quiz_order (school_name, quiz_password_id);

-- optional function/trigger to keep updated_at current
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger school_quiz_order_updated_at
    before update on public.school_quiz_order
    for each row execute procedure public.set_updated_at();
