-- Create admin_documents table
CREATE TABLE IF NOT EXISTS admin_documents (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  document_name VARCHAR(255) NOT NULL,
  document_type VARCHAR(50) NOT NULL CHECK (document_type IN ('pdf', 'word', 'excel')),
  file_path VARCHAR(500) NOT NULL,
  file_size BIGINT,
  uploaded_by UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Create unified admin_contacts table for both contacts and patrons
CREATE TABLE IF NOT EXISTS admin_contacts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  contact_type VARCHAR(50) NOT NULL CHECK (contact_type IN ('contact', 'patron')),
  name VARCHAR(255) NOT NULL,
  batch INTEGER,
  contact_no VARCHAR(20),
  patron_no VARCHAR(50),
  description TEXT,
  created_by UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Create storage bucket for admin documents (if not already exists)
-- This is typically done through the Supabase dashboard, but here's the SQL reference:
-- INSERT INTO storage.buckets (id, name, public) VALUES ('admin-documents', 'admin-documents', false);

-- Set up RLS (Row Level Security) policies for admin_documents
ALTER TABLE admin_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow super_admin to view and manage admin documents" ON admin_documents
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM members
      WHERE members.auth_user_id = auth.uid() AND members.role = 'super_admin'
    )
  );

-- Set up RLS for unified admin_contacts table
ALTER TABLE admin_contacts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow super_admin to view and manage admin contacts" ON admin_contacts
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM members
      WHERE members.auth_user_id = auth.uid() AND members.role = 'super_admin'
    )
  );

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_admin_documents_uploaded_by ON admin_documents(uploaded_by);
CREATE INDEX IF NOT EXISTS idx_admin_documents_created_at ON admin_documents(created_at);
CREATE INDEX IF NOT EXISTS idx_admin_contacts_type_created ON admin_contacts(contact_type, created_at);
CREATE INDEX IF NOT EXISTS idx_admin_contacts_created_by ON admin_contacts(created_by);
CREATE INDEX IF NOT EXISTS idx_admin_contacts_batch ON admin_contacts(batch);
CREATE INDEX IF NOT EXISTS idx_admin_contacts_patron_no ON admin_contacts(patron_no);
